FLASK_AI/DAY10_23/DBWEB/models/models.py
# -----------------------------------------------------------------
# 데이터베이스의 테이블 정의 클래스
# -----------------------------------------------------------------
from DBWEB import DB

# -----------------------------------------------------------------
# Question 테이블 정의 클래스
# -----------------------------------------------------------------
class Question(DB.Model):
    # 컬럼 정의
    id = DB.Column(DB.Integer, primary_key=True)
    subject = DB.Column(DB.String(200),nullable=False)
    content = DB.Column(DB.Text(),nullable=False)
    create_date = DB.Column(DB.DateTime(),nullable=False)

class Answer(DB.Model):
    id = DB.Column(DB.Integer,primary_key=True)
    question_id = DB.Column(DB.Integer,
                            DB.ForeignKey('question.id', ondelete='CASCADE'))
    question = DB.relationship('Question',backref=DB.backref('answer_set',))
    content = DB.Column(DB.Text(),nullable=False)
    create_date = DB.Column(DB.DateTime(),nullable=False)

FLASK_AI/DAY10_23/DBWEB/__init__.py
# 모듈 로딩 --------------------------------------------------------
from flask import Flask

# DB관련 설정
import config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

DB = SQLAlchemy() # 실제 DB 생성하는 애
MIGRATE = Migrate() # DB 컨트롤 하는 애



# -----------------------------------------------------------------
# Application 생성 함수
# - 함수명 : create_app <== 이름 변경 불가!!
# 사용자 정의함수 ----------------------------------------------------
def create_app():
    # Flask Web Server 인스턴스 생성
    APP = Flask(__name__)

    # DB 관련 초기화 설정
    APP.config.from_object(config)

    # DB 초기화 및 연동
    DB.init_app(APP) # 이 데이터 베이스랑 APP이랑
    MIGRATE.init_app(APP,DB) # 실제 DB랑 APP이랑 초기화 시켜서 연결해달라 ----> 여기까지가 기본 설정.

    # DB 클래스 정의 모듈 로딩
    from .models import models
    #    .폴더명

    
    # URL 처리 모듈 등록
    from .views import main_view,answer_views
    APP.register_blueprint(main_view.mainBP)
    APP.register_blueprint(answer_views.bp)
    return APP

    

# # 조건부 실행 -------------------------------------------------------
# if __name__ == '__main__':
#     # Flask Web Server 구동
#     app=create_app()
#     app.run()

'''/ <-- 루트 root : SW의 시작 폴더, Linux/Mac 저장소 시작점'''

FLASK_AI/DAY10_23/DBWEB/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request
from werkzeug.utils import redirect

from DBWEB import DB
from DBWEB.models.models import Answer, Question

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=('POST',))
def create(question_id) :
    question = Question.query.get_or_404(question_id)
    content = request.form['content']
    answer = Answer(content=content, create_date=datetime.now())
    question.answer_set.append(answer)
    DB.session.commit()
    return redirect(url_for('MAIN.questionItem', qid=question_id))

FLASK_AI/DAY10_23/DBWEB/views/main_view.py
# --------------------------------------------------------
# Flask Framework에서 '/'URL에 대한 라우팅 처리 파일
# - 파일명 : main_views.py
# --------------------------------------------------------
# 모듈 로딩------------------------------------------------
from flask import Blueprint, render_template
from DBWEB.models.models import Question

# Blueprint 인스턴스 생성
mainBP = Blueprint('MAIN',
                   import_name=__name__,
                   url_prefix='/',
                   template_folder='templates')

# http://localhost:8080/  URL 처리 라우팅 함수 정의
@mainBP.route('/')
def index():
    return render_template('index.html',name='홍길동')


# Question_view 관련 부분
# http://localhost:8080/  URL 처리 라우팅 함수 정의
@mainBP.route('/qlist')
def printlist():
    ## DB에서 조회한 결과를 HTML 파일로 전달
    q_list=Question.query.all()
    return render_template('question_list.html',question_list=q_list)

# http://localhost:8080/qdetail/<int:id>  URL 처리 라우팅 함수 정의
@mainBP.route('/qdetail/<int:qid>')
def questionItem(qid):
    ## DB에서 조회한 1개의 question 인스턴스를 전달
    q=Question.query.get(qid)
    return render_template('question_detail.html',question=q)

FLASK_AI/DAY10_23/DBWEB/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>★ MYWEB ★</title>
</head>
<body>
    <h1>Good Luck</h1>
    {{name}}님! 좋은하루 되세요!
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/style.css')}}">
</body>
</html>

FLASK_AI/DAY10_23/DBWEB/templates/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>★ MYWEB ★</title>
</head>
<body>
    <h1>질문상세보기</h1>
    <div id="'qDIV">
        <label>제목:</label>
        {{question.subject}}<br><br>

        <label>내용 : </label>
        {{question.content}}<br>
    </div>
    <h5>{{question.answer_set|length}}개의 답변이 있습니다.</h5>
    <div>
        <ul>
            {% for answer in question.answer_set %}
            <li>{{answer.content}}</li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <form action="{{url_for('answer.create', question_id=question.id)}}" method='post'>
            <textarea name="content" id="content" rows="15"></textarea>
            <input type="submit" value="답변등록">
        </form>

    <!-- </div>

    <h1>{{question.subject}}</h1>

    <div>
        {{question.content}}
    </div> -->


</body>
</html>

FLASK_AI/DAY10_23/DBWEB/templates/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>★ MYWEB ★</title>
</head>
<body>
    <h1>질문 게시판</h1>
    <table>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>날짜</th>
        </tr>
        {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>{{question.id}}</td>
                <td><a href="http://127.0.0.1:5000/qdetail/{{question.id}}">{{question.subject}}</a></td>
                <td>{{question.create_date}}</td>
            </tr>                                      <!-- Question 한 개가 한 개의 행-->  
            {% endfor %}
        
        {% else %}
        <tr>
            <td class='msg' colspan="'3">등록된 질문이 없습니다.</td>
        </tr>
        {% endif %}
    </table>

    <br><br>
    {% if question_list %}
    <ol>
        {% for question in question_list %}
        <li>{{question.subject}}</li>
        {% endfor %}
    </ol>
    {% else %}
    <p class='msg'>등록된 질문이 없습니다.</p>
    {% endif %}
</body>
</html>